/**
  ******************************************************************************
  * file           : main.c
  * brief          : STM32C542CCT6 + IIS3DWB IIC polling example (HAL2).
  ******************************************************************************
  * Copyright (c) 2025 STMicroelectronics.
  * All rights reserved.
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  ******************************************************************************
  */

/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include "mx_gpio_default.h"
#include "mx_i2c1.h"
#include "mx_usart1.h"
#include "iis3dwb_reg.h"
#include <stdio.h>
#include <string.h>

/* Private define ------------------------------------------------------------*/
#define BOOT_TIME               20U
#define POLL_TIME               100U
#define RESET_TIMEOUT           100U
#define IIS3DWB_I2C_ADDR     (0x6AU << 1) /* SA0 = Low; HAL address = 0xD4 */

/* PB6 = I2C1_SCL, PB7 = I2C1_SDA, PB0 = CS, PA1 = SA0.
 * CubeMX: CS 推挽输出，初始 High；SA0 推挽输出，初始 Low。
 * SCL/SDA 使用外部上拉。snprintf 的小数输出需要浮点格式支持。
 * IIS3DWB IIC 按数据手册使用单轴模式，本例读取 Z 轴和温度。
 * IIS3DWB_I2C_ADD_L/H 已含地址位和读位，不要将其再次左移。
 */

/* Private variables ---------------------------------------------------------*/
static int16_t data_raw_acceleration[3];
static int16_t data_raw_temperature;
static float_t acceleration_mg;
static float_t temperature_degC;
static uint8_t whoamI, rst;
static uint8_t tx_buffer[200];

/* Private functions prototype -----------------------------------------------*/
static int32_t platform_write(void *handle, uint8_t reg, const uint8_t *bufp,
                              uint16_t len);
static int32_t platform_read(void *handle, uint8_t reg, uint8_t *bufp,
                             uint16_t len);
static void tx_com(uint8_t *tx_buffer, uint16_t len);
static void platform_delay(uint32_t ms);
static void platform_init(void);

/**
  * brief:  The application entry point.
  */
int main(void)
{
  stmdev_ctx_t dev_ctx = {0};
  uint32_t reset_start;
  int32_t ret;

  /* Initialize the system and peripherals generated by CubeMX. */
  if (mx_system_init() != SYSTEM_OK)
  {
    return (-1);
  }
  platform_init();

  /* Initialize MEMS driver interface. */
  dev_ctx.write_reg = platform_write;
  dev_ctx.read_reg = platform_read;
  dev_ctx.mdelay = platform_delay;
  dev_ctx.handle = mx_i2c1_i2c_gethandle();

  /* Check device ID. */
  ret = iis3dwb_device_id_get(&dev_ctx, &whoamI);
  snprintf((char *)tx_buffer, sizeof(tx_buffer),
           "IIS3DWB_ID=0x%02X, id=0x%02X\r\n",
           (unsigned int)IIS3DWB_ID, (unsigned int)whoamI);
  tx_com(tx_buffer, (uint16_t)strlen((char *)tx_buffer));
  if ((ret != 0) || (whoamI != IIS3DWB_ID))
  {
    return (-1);
  }

  /* Restore default configuration and wait for reset completion. */
  ret = iis3dwb_reset_set(&dev_ctx, PROPERTY_ENABLE);
  reset_start = HAL_GetTick();
  while (ret == 0)
  {
    ret = iis3dwb_reset_get(&dev_ctx, &rst);
    if ((ret != 0) || (rst == 0U))
    {
      break;
    }
    if ((uint32_t)(HAL_GetTick() - reset_start) >= RESET_TIMEOUT)
    {
      ret = -1;
      break;
    }
    platform_delay(1U);
  }
  platform_delay(BOOT_TIME);

  /* DS12569 specifies IIC use in single-axis mode. Select Z before ODR on.
   * Enable IIC, auto-increment, BDU, +/-2 g and the 6.3 kHz low-pass path.
   */
  if ((ret != 0) ||
      (iis3dwb_i2c_interface_set(&dev_ctx, IIS3DWB_I2C_ENABLE) != 0) ||
      (iis3dwb_auto_increment_set(&dev_ctx, PROPERTY_ENABLE) != 0) ||
      (iis3dwb_block_data_update_set(&dev_ctx, PROPERTY_ENABLE) != 0) ||
      (iis3dwb_xl_full_scale_set(&dev_ctx, IIS3DWB_2g) != 0) ||
      (iis3dwb_xl_axis_selection_set(&dev_ctx, IIS3DWB_ONLY_Z_ON_ONE_OUT_REG) != 0) ||
      (iis3dwb_xl_filt_path_on_out_set(&dev_ctx, IIS3DWB_LP_6k3Hz) != 0) ||
      (iis3dwb_xl_data_rate_set(&dev_ctx, IIS3DWB_XL_ODR_26k7Hz) != 0))
  {
    snprintf((char *)tx_buffer, sizeof(tx_buffer),
             "IIS3DWB initialization error\r\n");
    tx_com(tx_buffer, (uint16_t)strlen((char *)tx_buffer));
    return (-1);
  }
  platform_delay(BOOT_TIME);
  snprintf((char *)tx_buffer, sizeof(tx_buffer),
           "IIS3DWB IIC: Z axis, +/-2 g, ODR=26.7 kHz\r\n");
  tx_com(tx_buffer, (uint16_t)strlen((char *)tx_buffer));

  /* Poll recent samples for display; this does not capture every ODR sample. */
  while (1)
  {
    iis3dwb_status_reg_t status = {0};

    /* Read ready output registers before conversion and serial output. */
    ret = iis3dwb_status_reg_get(&dev_ctx, &status);
    if ((ret == 0) && (status.xlda != 0U))
    {
      ret = iis3dwb_acceleration_raw_get(&dev_ctx, data_raw_acceleration);
    }
    if ((ret == 0) && (status.tda != 0U))
    {
      ret = iis3dwb_temperature_raw_get(&dev_ctx, &data_raw_temperature);
    }
    if (ret != 0)
    {
      snprintf((char *)tx_buffer, sizeof(tx_buffer),
               "IIS3DWB read error, retrying\r\n");
      tx_com(tx_buffer, (uint16_t)strlen((char *)tx_buffer));
      platform_delay(POLL_TIME);
      continue;
    }

    if (status.xlda != 0U)
    {
      /* The standard getter reads XYZ registers; only Z (index 2) is active. */
      acceleration_mg = iis3dwb_from_fs2g_to_mg(data_raw_acceleration[2]);
      snprintf((char *)tx_buffer, sizeof(tx_buffer),
               "Acceleration Z [mg]:%4.2f\r\n", (double)acceleration_mg);
      tx_com(tx_buffer, (uint16_t)strlen((char *)tx_buffer));
    }
    if (status.tda != 0U)
    {
      temperature_degC = iis3dwb_from_lsb_to_celsius(data_raw_temperature);
      snprintf((char *)tx_buffer, sizeof(tx_buffer),
               "Temperature [degC]:%6.2f\r\n", (double)temperature_degC);
      tx_com(tx_buffer, (uint16_t)strlen((char *)tx_buffer));
    }
    platform_delay(POLL_TIME);
  }
} /* end main */

/* Write generic device register (platform dependent). */
static int32_t platform_write(void *handle, uint8_t reg, const uint8_t *bufp,
                              uint16_t len)
{
  if ((handle == NULL) || (bufp == NULL) || (len == 0U))
  {
    return -1;
  }
  return (HAL_I2C_MASTER_MemWrite((hal_i2c_handle_t *)handle,
                                IIS3DWB_I2C_ADDR, reg,
                                HAL_I2C_MEM_ADDR_8BIT, bufp, len, 1000U)
          == HAL_OK) ? 0 : -1;
}

/* Read generic device register (platform dependent). */
static int32_t platform_read(void *handle, uint8_t reg, uint8_t *bufp,
                             uint16_t len)
{
  if ((handle == NULL) || (bufp == NULL) || (len == 0U))
  {
    return -1;
  }
  return (HAL_I2C_MASTER_MemRead((hal_i2c_handle_t *)handle,
                               IIS3DWB_I2C_ADDR, reg,
                               HAL_I2C_MEM_ADDR_8BIT, bufp, len, 1000U)
          == HAL_OK) ? 0 : -1;
}

/* Send data through USART1. */
static void tx_com(uint8_t *tx_buffer, uint16_t len)
{
  hal_uart_handle_t *huart1 = mx_usart1_uart_gethandle();
  if ((huart1 != NULL) && (tx_buffer != NULL) && (len != 0U))
  {
    (void)HAL_UART_Transmit(huart1, tx_buffer, len, 1000U);
  }
}

/* Platform specific delay. */
static void platform_delay(uint32_t ms)
{
  HAL_Delay(ms);
}

/* Set interface pins after mx_system_init(). */
static void platform_init(void)
{
  HAL_GPIO_WritePin(CS_PORT, CS_PIN, HAL_GPIO_PIN_SET);
  HAL_GPIO_WritePin(SA0_PORT, SA0_PIN, HAL_GPIO_PIN_RESET);
  platform_delay(BOOT_TIME);
}
